"""GitOps pull-request generation.

Turns a :class:`RemediationPlan` into a real (or dry-run) GitHub pull request
that proposes a Helm values change. Production deployments wire this to the
ArgoCD-watched repository; local runs default to ``dry_run=True`` and return
the proposal without touching GitHub.
"""

from __future__ import annotations

import logging
import re
from typing import Protocol

from .config import Settings, get_settings
from .models import IncidentAnalysis, PullRequestProposal
from .remediation import plan_to_helm_values_yaml

log = logging.getLogger(__name__)


_SLUG_RE = re.compile(r"[^a-z0-9-]+")


def _slug(value: str, max_len: int = 40) -> str:
    return _SLUG_RE.sub("-", value.lower()).strip("-")[:max_len]


def render_pr_body(analysis: IncidentAnalysis) -> str:
    plan = analysis.remediation_plan
    sim = analysis.simulation
    lines = [
        f"# AegisForge: {plan.title}",
        "",
        f"**Incident:** `{analysis.incident_id}`  ",
        f"**Event:** `{analysis.event.event_id}` ({analysis.event.severity.value} "
        f"{analysis.event.event_type.value})  ",
        f"**Cluster:** `{analysis.event.cluster}`  "
        f"**Namespace:** `{analysis.event.namespace}`  "
        f"**Workload:** `{analysis.event.workload}`  ",
        "",
        "## Executive summary",
        analysis.executive_summary,
        "",
        "## Root cause hypothesis",
        analysis.root_cause_hypothesis,
        "",
        "## Proposed actions",
    ]
    lines += [f"- {a}" for a in plan.actions]
    lines += [
        "",
        "## Digital twin simulation",
        f"- status: `{sim.status}`",
        f"- blast radius: `{sim.estimated_blast_radius}`",
        f"- risk score: `{sim.risk_score}/100`",
        f"- safe to auto-apply: `{sim.safe_to_auto_apply}`",
    ]
    if sim.policy_violations:
        lines += ["", "### Policy violations"]
        lines += [f"- {v}" for v in sim.policy_violations]

    rollback_lines = [f"- {step}" for step in plan.rollback_plan] or ["- (none)"]
    lines += [
        "",
        "## Rollback plan",
        *rollback_lines,
        "",
        "## Reasoning provided by",
        f"- provider: `{analysis.llm_provider}`",
        f"- model: `{analysis.llm_model}`",
        "",
        "_Generated by AegisForge. Approval required before merge._",
    ]
    return "\n".join(lines)


def build_proposal(analysis: IncidentAnalysis, settings: Settings) -> PullRequestProposal:
    """Construct the proposal regardless of whether we have credentials."""

    repo = settings.github_repository or "example-org/example-repo"
    branch = (
        f"aegisforge/{_slug(analysis.event.event_id)}-"
        f"{_slug(analysis.remediation_plan.title)}"
    )
    workload = analysis.event.workload or "workload"
    namespace = analysis.event.namespace or "default"
    values_yaml = plan_to_helm_values_yaml(analysis.remediation_plan)

    files = {
        f"environments/{analysis.event.cluster}/{namespace}/{workload}/values.yaml": values_yaml,
    }
    return PullRequestProposal(
        repository=repo,
        branch=branch,
        base=settings.github_base_branch,
        title=f"[AegisForge] {analysis.remediation_plan.title}",
        body=render_pr_body(analysis),
        files=files,
        dry_run=settings.github_dry_run,
    )


class GithubClient(Protocol):
    def open_pull_request(self, proposal: PullRequestProposal) -> str: ...


class PyGithubClient:
    """Real PyGithub-backed client."""

    def __init__(self, token: str) -> None:
        try:
            from github import Github  # type: ignore
        except ImportError as exc:  # pragma: no cover
            raise RuntimeError("PyGithub is not installed") from exc
        self._gh = Github(token)

    def open_pull_request(self, proposal: PullRequestProposal) -> str:  # pragma: no cover - network
        repo = self._gh.get_repo(proposal.repository)
        base_ref = repo.get_branch(proposal.base)
        try:
            repo.create_git_ref(ref=f"refs/heads/{proposal.branch}", sha=base_ref.commit.sha)
        except Exception as exc:
            log.warning("branch may already exist: %s", exc)
        for path, content in proposal.files.items():
            try:
                existing = repo.get_contents(path, ref=proposal.branch)
                repo.update_file(
                    path=path,
                    message=f"AegisForge: update {path}",
                    content=content,
                    sha=existing.sha,
                    branch=proposal.branch,
                )
            except Exception:
                repo.create_file(
                    path=path,
                    message=f"AegisForge: create {path}",
                    content=content,
                    branch=proposal.branch,
                )
        pr = repo.create_pull(
            title=proposal.title,
            body=proposal.body,
            head=proposal.branch,
            base=proposal.base,
            draft=True,
        )
        return pr.html_url


async def propose_pull_request(
    analysis: IncidentAnalysis,
    settings: Settings | None = None,
    client: GithubClient | None = None,
) -> PullRequestProposal:
    """Build and (optionally) open a PR. Returns the proposal with URL populated."""

    settings = settings or get_settings()
    proposal = build_proposal(analysis, settings)

    if proposal.dry_run or not settings.github_token or not settings.github_repository:
        proposal.url = f"dry-run://{proposal.repository}/{proposal.branch}"
        return proposal

    try:
        gh = client or PyGithubClient(settings.github_token)
        proposal.url = gh.open_pull_request(proposal)
    except Exception as exc:
        log.exception("failed to open PR, returning proposal only: %s", exc)
        proposal.url = f